### PR TITLE
Fixed scraping from arzon.jp

### PR DESCRIPTION
**Pull request by SwedishGojira**
Updated the scraper so it works for me. just had to replace a few http with https and .htm with .html.

### CODE REVIEW

**Comment by centalinetht** [comment]
it works! thx a lot!

**Comment by gkharry** [comment]
I have some trouble with this script. All the titles are "found", and there's still no poster scraped.

**Comment by SwedishGojira** [comment]
@gkharry Did you try my fork? https://github.com/SwedishGojira/javscraper
I have updated it and scanned over 3658 titles with no problem what so ever using my fork. Tried it on OSX, Linux and Windows.

**Comment by gkharry** [comment]
It works :)

**Pull request merged**
